/** Analysis results display panel */
import React from 'react'

const AnalysisPanel = ({ analysis }) => {
  if (!analysis) return null

  const { sequence_type, length, counts, gc_percent, at_percent, source_type, source_identifier } = analysis

  const generatePDFReport = () => {
    const reportDate = new Date().toLocaleString()
    const countsTable = Object.entries(counts).map(([base, count]) => {
      const percentage = length > 0 ? ((count / length) * 100).toFixed(2) : 0
      return `<tr><td>${base}</td><td>${count.toLocaleString()}</td><td>${percentage}%</td></tr>`
    }).join('')

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>OpenGenViz Analysis Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; }
    h1 { color: #2c3e50; }
    h2 { color: #34495e; border-bottom: 2px solid #3498db; padding-bottom: 5px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #3498db; color: white; }
    .metric { margin: 10px 0; padding: 10px; background-color: #f8f9fa; border-left: 4px solid #3498db; }
    .label { font-weight: bold; color: #555; }
  </style>
</head>
<body>
  <h1>OpenGenViz Analysis Report</h1>
  <p><strong>Generated:</strong> ${reportDate}</p>
  
  <h2>Analysis Metadata</h2>
  <div class="metric"><span class="label">Sequence Type:</span> ${sequence_type}</div>
  <div class="metric"><span class="label">Length:</span> ${length.toLocaleString()} bases</div>
  ${gc_percent !== null && gc_percent !== undefined ? `<div class="metric"><span class="label">GC%:</span> ${gc_percent.toFixed(2)}%</div>` : ''}
  ${at_percent !== null && at_percent !== undefined ? `<div class="metric"><span class="label">${sequence_type === 'RNA' ? 'AU%' : 'AT%'}:</span> ${at_percent.toFixed(2)}%</div>` : ''}
  ${source_identifier ? `<div class="metric"><span class="label">Source:</span> ${source_type === 'upload' ? 'File Upload' : 'Database Fetch'} - ${source_identifier}</div>` : ''}
  
  <h2>Composition Analysis</h2>
  <table>
    <thead>
      <tr>
        <th>Base/Amino Acid</th>
        <th>Count</th>
        <th>Percentage</th>
      </tr>
    </thead>
    <tbody>
      ${countsTable}
    </tbody>
  </table>
  
  <p style="margin-top: 30px; font-size: 12px; color: #777;">
    Report generated by OpenGenViz - Genomic Analysis Platform
  </p>
</body>
</html>`

    const printWindow = window.open('', '_blank')
    printWindow.document.write(htmlContent)
    printWindow.document.close()
    printWindow.focus()
    // Wait for content to load, then trigger print dialog (which allows saving as PDF)
    setTimeout(() => {
      printWindow.print()
    }, 250)
  }

  return (
    <div className="panel">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h2 className="panel-title">Analysis Results</h2>
        <button
          className="btn"
          onClick={generatePDFReport}
          style={{ padding: '0.5rem 1rem', fontSize: '0.9rem' }}
        >
          📄 Generate PDF Report
        </button>
      </div>
      
      <div className="analysis-metrics">
        <div className="metric-card">
          <div className="metric-label">Sequence Type</div>
          <div className="metric-value" style={{ fontSize: '1.2rem' }}>
            {sequence_type}
          </div>
        </div>
        <div className="metric-card">
          <div className="metric-label">Length</div>
          <div className="metric-value">{length.toLocaleString()}</div>
        </div>
        {gc_percent !== null && gc_percent !== undefined && (
          <div className="metric-card">
            <div className="metric-label">GC%</div>
            <div className="metric-value">{gc_percent.toFixed(2)}%</div>
          </div>
        )}
        {at_percent !== null && at_percent !== undefined && (
          <div className="metric-card">
            <div className="metric-label">{sequence_type === 'RNA' ? 'AU%' : 'AT%'}</div>
            <div className="metric-value">{at_percent.toFixed(2)}%</div>
          </div>
        )}
      </div>

      {source_identifier && (
        <div className="source-info">
          <strong>Source:</strong> {source_type === 'upload' ? 'File Upload' : 'Database Fetch'} - {source_identifier}
        </div>
      )}

      <div style={{ marginTop: '1.5rem' }}>
        <h3 style={{ marginBottom: '0.5rem' }}>Building Block Counts</h3>
        <p className="helper-text" style={{ marginBottom: '1rem', fontSize: '0.9rem', color: '#666' }}>
          This table shows exactly how many times each building block appears in your sequence and what percentage of the total it represents.
        </p>
        <table className="table">
          <thead>
            <tr>
              <th>Base/Amino Acid</th>
              <th>Count</th>
              <th>Percentage</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(counts).map(([base, count]) => {
              const percentage = length > 0 ? ((count / length) * 100).toFixed(2) : 0
              return (
                <tr key={base}>
                  <td><strong>{base}</strong></td>
                  <td>{count.toLocaleString()}</td>
                  <td>{percentage}%</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default AnalysisPanel

